format:
- type: spachat:tags
- type: spachat:withClick
  action: SUGGEST_COMMAND
  value-format:
  - type: spachat:string
    value: '/tell '
  - type: minecraft:realname
  format:
  - type: spachat:name
- type: spachat:string
  value: ': '
- type: minecraft:message
ranks:
  default:
    name-color: GRAY
    sorting-order: 0
    priority: 0
  admin:
    name-color: WHITE
    sorting-order: 1
    priority: 1
    tag-format:
    - type: spachat:withClick
      format:
      - type: spachat:withHover
        format:
        - type: spachat:string
          value: '[Admin]'
          color: DARK_RED
        action: SHOW_TEXT
        value-format:
        - type: spachat:string
          value: 'Custom tooltip: '
        - type: spachat:meta
          name: message
      action: OPEN_URL
      format:
      - type: spachat:meta
        name: link
worlds:
- world-World
- world_nether-World
- world_the_end-World
